// ==UserScript==
// @name          pink v3rm
// @namespace     https://v3rmillion.net
// @description	  hell is full https://greasyfork.org/en/scripts/371842-pink-v3rmillion-v1/code
// @author        ??
// @homepage      ??
// @include       https://v3rmillion.net*
// @include       https://v3rmillion.net/siterules.php
// @include       https://v3rmillion.net/legal.html
// @include       https://v3rmillion.net/removals/
// @run-at        document-start
// @version       69
// ==/UserScript==
(function() {var css = "";
if (false || (document.location.href.indexOf("https://v3rmillion.net") == 0))
	css += [
		"  .pm_new, .alert_new",
		"  {",
		"    background:  #ff00d0 !important;",
		"  }",
		"",
    "  a.postbit_qdelete, a.postbit_website, a.postbit_reply_pm, a.postbit_forward_pm, a.postbit_delete_pm, a.postbit_email, a.postbit_pm, a.postbit_find, a.postbit_edit, a.postbit_quote, a.postbit_multiquote, a.postbit_multiquote_on, a.postbit_report",
		"  {",
		"    background: #ff00d0 !important;",
		"    border: 1px solid #ba0499 !important;",
		"  }",
		"",
		"  a.button.new_thread_button, button, form input.button, a.button:link, a.button:visited, a.button:active, button new_reply_button",
		"  {",
		"    background: #ff00d0 !important;",
		"    border: 1px solid #ba0499 !important;",
		"  }",
		"",
		"  a.button.new_thread_button:hover, button, input.button:hover, a.button:hover",
		"  {",
		"    transition: background 0.2s ease, border 0.2s ease;",
		"    background: #ffffff;",
		"    border: 1px solid #ffffff;",
		"  }",
		"",
    "  .buttons",
		"  {",
		"    border: #f900cb;",
		"  }",
		"",
    "  input.buttons",
    "  {",
    "  background-color: rgba(32,32,32,.2) !important;",
    "  }",
    "",
		"  #bridge",
		"  {",
		"    border-bottom: 5px solid #ff00d0;",
		"  }",
		"",
		"  ul.menu li ul, .panel_buttons",
		"  {",
		"    border-top: 5px solid  #ff00d0;",
		"  }",
		"",
		"  .pagination .pagination_current",
		"  {",
		"    background: #ff00d0 !important;",
		"    border: 1px solid #ff00d0 !important;",
		"    border-radius: 2px !important;",
		"  }",
		"",
		"  .pagination a",
		"  {",
		"    background:  #ff00d0 !important;",
		"    border: 1px solid  #ff00d0 !important;",
		"  }",
		"",
		"  .pagination a:hover",
		"  {",
		"    transition: background 0.2s ease, border 0.2s ease;",
		"    background: #ff00d0;",
		"    border: 1px solid  #ff00d0;",
		"  }",
		"",
		"  .thead, .tfoot",
		"  {",
		"    background:  #ff00d0 !important;",
		"  }",
		"",
		"  .popup_menu .popup_item:hover",
		"  {",
		"    color: #ff00d0;",
		"  }",
		"",
		"  .buttons:hover",
		"  {",
		"    transition: border 0.2s ease !important;",
		"    background: #ff00d0 !important;",
		"    cursor: pointer !important;",
		"  }",
		"",
		" tr td.thead",
		"  {",
		"    background: #c900a4 !important;",
		"  }",
		"",
		"  .usercp_nav_item:before",
		"  {",
		"    color: #ff00d0;",
		"  }",
		"",

		"  .thead input.textbox, .thead select,a.postlink",
		"  {",
		"    border:solid thin #ff00d0 !important;",
		"  }",
		"",
    " tr td.tfoot input.buttons",
		"  {",
		"    border:1px #ff00d0 !important;",
    "    background-color: rgba(32,32,32,.3) !important;",
		"  }",
		"",
		"  ul.menu li a:hover, .panel_buttons a:hover, ul.menu li ul li a:hover",
		"  {",
		"    transition: background 0.5s ease;",
		"    background: #ff00d0;",
		"  }",
		"",
		"  .thread_head",
		"  {",
		"    border-bottom: 5px solid #f900cb !important;",
		"  }",
		"",
		"  #footer",
		"  {",
		"    border-top: 5px solid #ff00d0;",
		"  }",
		"",
		"  .forum_on",
		"  {",
		"    color: #ff00d0;",
		"  }",
		"",
		"  .forum_off",
		"  {",
		"    color: #ff00d0;",
		"  }",
		"",
		"  .cRem a:visited, .cRem a:link",
		"  {",
		"    color: #ff00d0 !important;",
		"  }",
		"",
		"  .inline_row a:visited, .inline_row a",
		"  {",
		"    color: #ff00d0 !important;",
		"  }",
		"",
		"  input.textbox:focus",
		"  {",
		"    transition: border 0.2s ease, box-shadow 0.2s ease;",
		"    border: 1px solid #ff00d0;",
		"    box-shadow: 0 0 10px #ff00d0;",
		"  }",
		"",
		"  form #message:focus",
		"  {",
		"    transition: border 0.2s ease, box-shadow 0.2s ease;",
		"    border: 1px solid #ff00d0;",
		"    box-shadow: 0 0 10px #ff00d0;",
		"  }",
		"",
		"  div#container span.smalltext a span strong",
		"  {",
		"    color: #ff00d0 !important;",
		"  }",
		"",
		"  .red_alert",
		"  {",
		"    background: #ff00d0;",
		"  }",
		"",
		"  .red_alert:hover",
		"  {",
		"    transition: background 0.5s ease;",
		"    background: #ff00d0;",
		"  }"
	].join("\n");
if (false || (location.href.replace(location.hash,'') == "https://v3rmillion.net/siterules.php") || (location.href.replace(location.hash,'') == "https://v3rmillion.net/legal.html") || (location.href.replace(location.hash,'') == "https://v3rmillion.net/removals/"))
	css += [
		"  .wrap",
		"  {",
		"    border: 1px solid #ff00d0;",
		"  }",
		"",
		"  .wrap a",
		"  {",
		"    color: #ff00d0;",
		"  }",
		"",
		"  .footer",
		"  {",
		"    background-color: #ff00d0;",
		"  }",
		"",
		"  .footer a",
		"  {",
		"    color: #ff00d0;",
		"  }",
		"",
		"  .footer a:hover",
		"  {",
		"    transition: color 0.1s ease;",
		"    color: #ff00d0;",
		"  }",
		"",
		"  a:link, a:visited",
		"  {",
		"    color: #ff00d0;",
		"  }",
		"",
		"  a:link:hover, a:visited:hover",
		"  {",
		"    color: #ff00d0;",
		"  }"
	].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
